### ISSUE TITLE
Issue on Asynchronous Validators with Deno

### ISSUE THREAD

**Issue by KirianCaumes** [neuledge/computed-types#76]
Hi,

I've found an issue with asynchronous validators.

For example, correct behavior like this:
```ts
import Schema, { string } from 'https://denoporter.sirjosh.workers.dev/v1/deno.land/x/computed_types/src/index.ts'
const UserSchema = {
    username: string.trim().normalize().between(7, 255),
};
const validator = Schema(UserSchema);
try {
    const user = await validator({ username: 'test' });
    console.log(user)
} catch (error) {
    console.log(error)
    console.log(error.errors[0])
    console.log(error.errors[0]?.error?.message)
    console.log(error.errors[0]?.path)
}
```
Print this in console, wich is ok:
```
ValidationError: username: Expect length to be between 7 and 255 characters (actual: 4)
    at toError (errors.ts:33:16)
    at createValidationError (errors.ts:51:34)
    at compiler.ts:102:23
    at test.ts:14:24
{
  error: RangeError: Expect length to be between 7 and 255 characters (actual: 4)
    at string.ts:36:35
    at toError (errors.ts:36:24)
    at validations.ts:25:19
    at Validator.ts:41:24
    at Array.<anonymous> (compiler.ts:58:40)
    at compiler.ts:96:37
    at test.ts:14:24,
  path: [ "username" ]
}
Expect length to be between 7 and 255 characters (actual: 4)
[ "username" ]
```

But with async like this:
```ts
import Schema, { string } from 'https://denoporter.sirjosh.workers.dev/v1/deno.land/x/computed_types/src/index.ts'
async function AvailableUsername(input: string) {
    throw new TypeError('my error')
}
const UserSchema = {
    username: AvailableUsername,
};
const validator = Schema(UserSchema);
try {
    const user = await validator({ username: 'test' });
    console.log(user)
} catch (error) {
    console.log(error)
    console.log(error.errors[0])
    console.log(error.errors[0]?.error?.message)
    console.log(error.errors[0]?.path)
}
```
Return this:
```
ValidationError: undefined
    at toError (errors.ts:33:16)
    at createValidationError (errors.ts:51:34)
    at compiler.ts:108:23
    at async test.ts:14:18
TypeError: my error
    at AvailableUsername (test.ts:4:11)
    at Array.<anonymous> (compiler.ts:58:40)
    at compiler.ts:96:37
    at test.ts:14:24
undefined
undefined
```

So asynchronous validators does not seems to work well with Deno :/

Any idea?

Thanks a lot!

**Comment by moshest** [comment]
Hi, thank you for the report.

I check this bug but I did manage to reproduce it on Node.js (See: 548ff93).

I'm thinking it may related to some versions update and fixes that deployed so I just released a new version v1.3.1
Can you try reproduce this error on Node.js environment as well?

**Comment by KirianCaumes** [comment]
Hi,

Thanks you answer!

I just tested again it with Deno and Node:

- It works with Node, but if I remember well, it already worked before.
- However it still doesn't seem to work with Deno.

I've tried to refresh your lib with this command, but I'm not sure if I'm doing well as I'm a very beginner with Deno.
```
deno cache --reload https://denoporter.sirjosh.workers.dev/v1/deno.land/x/computed_types/src/index.ts
```

However, if i throw an error like this in Deno, it works, but that's not an awesome solution:
```ts
throw {
    path: ["key"],
    error: new Error("my error")
}
```

Thanks for you help!

**Comment by moshest** [comment]
Thanks for verifying. I dig in and found deno.land added a webhook to install on repos. I didn't do that up until now so it didn't push any new updates to deno 🙀

I push a new verison and I verified it got updated on deno. Please kindly check again now :)

**Comment by KirianCaumes** [comment]
Hi,
Thank you very much for this, it works now!
